### ISSUE TITLE
$childNodes empty on cached viewhelper

### ISSUE THREAD

**Issue by b-strauss** [TYPO3/Fluid#259]
Hi, I just migrated my code from Typo3 7.6 to Typo3 8.4, In one of my ViewHelpers I access $childNodes to render some logic based on child viewhelpers. I just debugged and found out that $childNodes is empty in cached viewhelpers. How can I solve this?

**Comment by NamelessCoder** [comment]
Hey @b-strauss - child nodes only exist while the template is being compiled, so once compiled you can no longer use those. You've got two ways to solve this:

1. To work around the issue, override the `compile()` method and call `$compiler->disable()` which causes the TemplateCompiler to not store the compiled PHP class, instead parsing your template file and creating the nodes each time (this is less than ideal for performance). Example: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid/Classes/Core/Widget/AbstractWidgetViewHelper.php#L223
2. To properly solve this, implement the `compile()` method on your ViewHelper and make it produce the correct compiled code based on your child nodes. This should be possible to achieve for any use case, but it is not exactly easy to do. And you still need the logic which renders your ViewHelper before it gets compiled (for this case it's often best to override `render()` and make that assume it is always called before being compiled, but that's probably how your VH already looks since you're accessing child nodes). I recommend taking a look at for example the AbstractConditionViewHelper's `compile()` method to see how nodes are converted into closures that are then compiled. This solution would be the ideal solution for performance.

PS: for ViewHelpers which don't need child node access you can implement `renderStatic` and implement the new Trait `CompileWithRenderStatic` from Fluid, this makes your ViewHelper compile to a straight `renderStatic` call and is a good compromise between best performance and least code.

**Comment by b-strauss** [comment]
Thank you very much for the detailed and fast answer!
