### ISSUE TITLE
Limit to objectaccess

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/Fluid#261]
Mostly a question: is it possible to lock down Fluid to only allow e.g. object accessors, thus leaving all regular and inline viewhelper calls as is?

Background: from time to time I'm thinking about templates where the user should be able to put some data output at arbitrary locations but without being able to invoke viewhelpers, think mail templates.

**Comment by NamelessCoder** [comment]
The only solution I can think of is a custom ViewHelperResolver which silently ignores every namespace regardless of whether it's declared or not, including the built-in Fluid namespace.

Whether or not that has side effects is another matter altogether... but, it *should* work (knock on wood) in particular because we no longer use ViewHelperNode wrapping to achieve value escaping (pads self on back).

**Comment by mbrodala** [comment]
Sounds reasonable, I'll keep this in mind. Thanks a lot. :-)
