### ISSUE TITLE
Compressing and concatenating Assets

### ISSUE THREAD

**Issue by r4fx** [TYPO3/Fluid#281]
I working with new feature of fluid standalone called Header/Footer Assets (https://docs.typo3.org/typo3cms/extensions/core/8-dev/Changelog/8.6/Feature-79413-AutorenderAssetSectionsInFluidTemplateContentObject.html), and discovered that files included with that methods are ignored by compressing and concatenating using any available native options and fews extensions.

Are there plans for the future to extend handling assets with options like concatenating and compressing ?

**Comment by NamelessCoder** [comment]
I'm afraid this isn't the right place to ask this question. The feature you mention only relates to Fluid in that TYPO3 CMS calls `renderSection` which renders your asset sections, the rest has nothing to do with Fluid.

There are a few places you could ask this question, see https://typo3.org/support/ for a list. I would probably suggest StackOverflow and tagging the question with `typo3` since there may be a way through configuration or third-party extensions to TYPO3 CMS.
