### ISSUE TITLE
MathExpressionNode inside f:alias or f:for doesn't find local variables

### ISSUE THREAD

**Issue by christoph-bessei** [TYPO3/Fluid#300]
I tried to use a math expression inside f:alias and f:for, but always get an "A non-numeric value encountered" error. 
The problem seems to be the rendering context in [MathExpressionNode](https://github.com/TYPO3/Fluid/blob/055303e18659978ac991885d9c8f6407fa4c6e63/src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php#L51), which doesn't know the variables set by f:for or f:alias but only the global variables. Since it can't find the variable it returns the variable name, which is not a numeric value.

Example:
```html
<f:alias map="{itemCount: '10'}">
    {itemCount / 2}
</f:alias>

<f:for each="{0:'10',1:'5'}" as="itemCount">
    {itemCount / 2}
</f:for>
```

I'm using fluid inside TYPO3 8.7.1 (composer install), so it could be a TYPO3 problem.
Is there an easy way to check if this also occurs in fluid standalone?

**Comment by liayn** [comment]
We encountered a similar issue with the following construction

```
	<f:for each="{0: 1, 1: 2, 2: 3}" as="value" iteration="it">
		<f:alias map="{nextIndex: '{it.index + 1}'}">
			{nextIndex} foo<br />
		</f:alias>
	</f:for>
```

This caused an error where "it.index" is
> A non-numeric value encountered

The preconditions for this to fail is PHP 7.1 + typo3 development-preset.

Reason this fails is because:
`\TYPO3Fluid\Fluid\Core\Parser\TemplateParser::textAndShorthandSyntaxHandler` calls `$expressionNode->evaluate($this->renderingContext);`, where `$expressionNode` is `\TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\Expression\MathExpressionNode`.
At this parsing stage there are no variables in the context to resolve hence it tries to execute this PHP statement: `"it.index" + "1"`, which is obviously invalid in PHP 7.1. (in lower versions this results in `1`)

Moreover also the `"1"` being a string is critical during actual execution as it would trigger the same PHP warning.

Steps to do therefore are:
1.) Reconsider whether it is clever to run the evaluation during parsing
2.) Make `\TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\Expression\MathExpressionNode::evaluateOperation` type aware and validate the parameters and cast them accordingly.

**Comment by NamelessCoder** [comment]
Superficial comments:

1) Evaluating expression nodes during parsing happens mostly for one (legacy) reason, the LegacyNamespaceExpressionNode from TYPO3 CMS. To my knowledge there are no more implementations which require this (and the purpose that would fill can be filled by using template pre-processors or just manipulating the rendering context manually). *We could drop this, but doing so would be a breaking change*.

2) It wouldn't be necessary to make the expression node type aware, but what would be necessary is to prevent it from causing errors when a variable can't be resolved. Part of the problem is that the expression node uses a method which allows returning the "object path" that would normally be an ObjectAccessor, as text. E.g. `{doesNotExist + 1}` becomes `"doesNotExist" + 1` and fails, as you've noticed.

Making this type aware during evaluation seems to be the only solid way to prevent issues on PHP 7.1 and up. It would, I think, be sufficient to use `is_numeric() && !is_string()` and if that's false, cast the value (and maybe detect the type of cast by looking at the other side of the expression).

**Comment by liayn** [comment]
> Making this type aware during evaluation seems to be the only solid way to prevent issues on PHP 7.1

Yes, type awareness is crucial for such important parts of TYPO3.
Specifically the number detection should be something like `MathUtility::canBeInterpretedAs*` in Core.
Because if you cast, you need to know to which type. Casting pure integers to floats to do math might have undesired side effects as typically known from IEEE 754. Hence "only use float, if really needed".

> LegacyNamespaceExpressionNode

Is not longer part of TYPO3 v8!

**Comment by NamelessCoder** [comment]
I know that expression node isn't part of v8 anymore, I removed it IIRC ;)

> Because if you cast, you need to know to which type.

There are two (slightly different) cases in play:

1. In the case above that causes this particular error, this is caused by *parsing* which means the output of the node is discarded, so it isn't relevant which type it returns in this case.
2. The other case is if you operate on two different types of proper numeric values, in which case casting to the "lowest possible type" must be done.

Btw, if you didn't already know:

```php
$double = '1.4';
echo var_dump($double + 0);
```

Also casts the string in PHP 7.1 at least, to the expected type. That's one way to ensure numeric and compatible values on both sides. But it needs to be combined with `is_numeric` to weed out strings that don't contain numbers (and I guess make the expression return `0` in any such case?).

**Comment by liayn** [comment]
> Also casts the string in PHP 7.1 at least, to the expected type.

Did you check the PHP warnings too? It's the warning that hits us during dev.

**Comment by NamelessCoder** [comment]
Input script:

```php
<?php
$cast = 'bad';
echo var_dump($cast + 0);

$cast = '1.4';
echo var_dump($cast + 0);
```

Output:

```plain
PHP Warning:  A non-numeric value encountered in /Users/claus/test.php on line 3
PHP Stack trace:
PHP   1. {main}() /Users/claus/test.php:0

Warning: A non-numeric value encountered in /Users/claus/test.php on line 3

Call Stack:
    0.0002     353520   1. {main}() /Users/claus/test.php:0

/Users/claus/test.php:3:
int(0)
/Users/claus/test.php:6:
double(1.4)
```

When strings contain numeric data, the warning is not raised.

**Comment by liayn** [comment]
okay that's a good thing then.

**Comment by NamelessCoder** [comment]
That's very nice to know indeed - but it makes `is_numeric` essential to remember when using the trick.

**Comment by AndreasA** [comment]
I can confirm that issue with PHP 7.1 and TYPO3 CMS 8.7.9 still exists when using "f:render"
```
<f:render section="pages" arguments="{pages: allPages, level: 1}" />
<f:section name="pages">
 <f:if condition="{page.subPages}">
                        <ul>
                            <f:render section="pages" arguments="{pages: page.subPages, level: '{level + 1}'}" />
                        </ul>
                    </f:if>
</f:section>
```

Also results in the error when executiong '{level + 1}' as "level" doesn't seem to be interpreted yet, although I called the child with a valid integer level variable.

**Comment by sascha-egerer** [comment]
The problem is that "custom expressions" are called before viewhelpers are rendered.

That means they are executed on the rendering context the template is parsed with. Any modifications to the rendering context / variable container are not executed when expressions are parsed.

Fluid will first resolve all expressions like `{foo + 1}` and then render the nodes like viewhelpers. So that is broken by design...
```
    <f:variable name="foo" value="2" />
    {foo + 1}
```

See https://github.com/TYPO3/Fluid/blame/master/src/Core/Parser/TemplateParser.php#L606
That must not be called at this place but later when tags are parsed.

**Comment by foobar13373** [comment]
@sascha-egerer is right here. We have this problem, too (TYPO3 8.7.9 and PHP 7.1). This is not a question about whether a variable needs to be casted to circumvent the strict behaviour of PHP 7.1. Using more strict types is good, nevertheless - it's just not the root cause here. It'd fix the PHP warning, but the parsing order would still be wrong by design.

The problem here is that in specific situations the variables are not substituted by their finaly values before they are passed to teh MathExpressionNode. So the MathExpressionNode is called with `$left = 'templateVariableName' `instead of `$left = "1337"`.

In pre-PHP 7.1 this fell back to `$left = 0` through implicit casting in math context - which did not throw the warning, but still yielded wrong results.

**Comment by NamelessCoder** [comment]
A solution is planned, it will involve adding an interface to use in ExpressionNodes which need to be evaluated during parse-time; which will then be added to the appropriate node types only.

The other part of the issue is a side effect of parse-time evaluation and will disappear once that is solved, but it still has an effect in other node types. The desired behavior is to never fall back to treating a variable that's not found, as text, and to cast any null value as fas as possible.

@ foobar13373 

> Using more strict types is good, nevertheless - it's just not the root cause here.

Nobody claimed it was :) in fact, you're the first person to use the word "strict" in this thread. Right from the start of the issue it is clear we are aware of the actual problem. Which is not what you describe - what you describe is a side effect of the actual problem.

**Comment by foobar13373** [comment]
@NamelessCoder Thanks for the info.

You are right, the comments quickly took the direction to talk about casting and type behaviour of PHP 7.1, making me assume this was the actual consensus about the root cause here - which is not the case after scrolling back to top again. ;)

**Comment by foobar13373** [comment]
When will this patch be released?

**Comment by NamelessCoder** [comment]
> When will this patch be released?

@foobar13373 In the very next release which I'm expecting to be a simple bug-fix release. Thanks for helping out!

**Comment by BenjaminBeck** [comment]
For your Information:
I needed this and used it with TYPO3 8.7.2 & PHP 7.1.7
This code  ``var uid = {data.uid};``  used to work with PHP 7.0.? and did not get parsed with this commit on PHP 7.1.7:
```html
<v:asset.script name="init-ce-{data.uid}">
            (function(){
            	 var uid = {data.uid};
```
It needed to become:
```html
<v:asset.script name="init-ce-{data.uid}">
            (function()<f:format.raw>{</f:format.raw>
            	 var uid = {data.uid};
```
I am not sure if its the different PHP-Version or this commit that causes the difference in parsing. I am ok with this change, but it may break other templates if it goes into a patch-release ..

**Comment by NamelessCoder** [comment]
@BenjaminBeck are you certain this is related to the issue? I don't think it is. The type of change that would affect parsing like that, all exist in the regular expressions that read your template code. It's been several years since changes to those parts.

The problem reported in this issue is that when you use a math expression, `{var + 1}`, this gets evaluated too early and causes problems if `{var}` is not numeric. The difference in behavior between PHP versions is merely related to what constitutes an error when you attempt to cast something that isn't compatible - where PHP > 7.1 is a bit more strict and only allows compatible values. Hence, the removal of early evaluation solved that problem by never attempting to cast a variable that is not set (for example in side a loop or with f:alias as described).

So it really doesn't seem related...
