### ISSUE TITLE
Make empty string falsey for f:or

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/Fluid#337]
Currently the `f:or` viewhelper checks if its content is `null`, thus an empty string never triggers the `alternative` to be used. However, the viewhelper description says _If content is empty use alternative text_.

Thus I'd like to suggest to replace `null === $content` with `empty($content)` to also make empty strings trigger the `alternative`.

**Comment by sascha-egerer** [comment]
You must not use `empty` as this will also be true for `0`

**Comment by mbrodala** [comment]
OK, then maybe `$content === null || $content === ''`.

**Comment by NamelessCoder** [comment]
There's a tiny difference between `f:or` and normal condition, in that `f:or` isn't a condition as such, but rather a "if this variable isn't set, use/do this instead". It's actually supposed to allow rendering an empty string if an empty string is input, and it's allowed to use an empty array if one is returned from tag content.

I think we need to adapt the VH documentation so it doesn't use the word `empty` since that has implied PHP meaning.

...and I will happily consider a flag that makes for example `loose="1"` use straight up `empty($content)` to check whether to use `$content` or `$alternative` ;)

**Comment by lolli42** [comment]
Also see #389, which is essentially the same issue and adds more information why f:or tests for null.

**Comment by lolli42** [comment]
We updated the class docs with https://github.com/TYPO3/Fluid/pull/797 and will close here now.
