### ISSUE TITLE
if fails with check for empty strings

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3/Fluid#349]
`<f:if condition="{settings.tabletImage} != '' || {settings.mobileImage} != ''">` doesn't work and throws `A boolean expression has more than three parts.`

But `<f:if condition="{settings.tabletImage} || {settings.mobileImage}">` works.

We use TYPO3 7 and Fluid 7.6.23.

**Comment by NamelessCoder** [comment]
Hi Daniel,

Fluid on TYPO3 7.6 is not the standalone Fluid engine - it is an integrated part of the TYPO3 core and has several very significant differences. Among other things, the earlier versions of Fluid simply don't support multiple expression parts (and is probably not as refined in detecting the parts of the expression as the standalone version is).

If you can reproduce this problem on Fluid standalone we'll of course consider it. Otherwise, I'd say "won't fix" or "report to TYPO3" - but I'm not sure what the perspectives would be for getting a fluid bug fix into the TYPO3 7.6 branch. Technically, it is discontinued.

**Comment by DanielRuf** [comment]
Ok. That makes sense. I guess this is only available in TYPO3 8+.

I got used to the good Fluid Standalone and forgot that the old core version is not as good as Fluid Standalone.

I'll close the ticket as this is a TYPO3 core issue and the LTS 7 version is not supported anymore.
