### ISSUE TITLE
Discussion: Fluid port for other languages, especially javascript/nodejs

### ISSUE THREAD

**Issue by MajPay** [TYPO3/Fluid#352]
Hi!

I already asked this question via slack and wanted to create an issue here, so it does not get lost.

There is a very simple question, that bugs me lately: Is someone planning on a port of the fluid templating engine for other languages, such as javascript?

I love using fluid because some of my projects start with simple html (templating / theming) and will become TYPO3.CMS later. Some projects start as static pages and need to be integrated into a CMS later.

I decided to go with TYPO3.Fluid because i like it more than Twig/Smarty and all those curly-braces Template engines. XML is way better in my opinion.

The main benefit for my approach is, that i can reuse all written html in the CMS, simply copy&paste and be done with it. I can even add a fallback PartialRootPath/LayoutRootPath to reuse the code without having to copy anything.

For the moment i have a gulp task, that does the following:

```javascript
function fluidhtml() {
    return through.obj(function(file, encoding, callback){
        var sourcePath = file.path.replace(file.cwd, ".");
        exec('php src/php/scripts/build.php ' + sourcePath, function(error, stdout, stderr){
            if (error || stderr) {
                var errorMessage = stderr || error.toString();
                this.emit('error', new gutil.PluginError('templates', errorMessage));
            }
            file.contents = new Buffer(stdout);
            callback(null, file);
            console.info("built template " + sourcePath);
        }.bind(this));
    });
}

// ...

gulp.task('templates', function () {
    return gulp
        .src([
            'src/html/templates/*.html',
            'src/html/templates/**/*.html'
        ])
        .pipe(plumber(makeErrorLogger('templates')))
        .pipe(fluidhtml())
        .pipe(gulp.dest("public/static"));
});

```

This is working well on my local system, because i have php7 installed. But once someone has php5.5 or no php at all, building is not possible (my fluid implementation requires PHP >= 7.0). I could solve that by integrating a docker container for this, but then there is just another dependency instead of php.

So - to actually solve this in an elegant way - i think a javascript piort for the FLUID Standalone Template Engine would be a great deal.

It could also help fluid increase acceptance aside from TYPO3.

Tell me what you think about this and if there is work being done already...

Kind regards,
Philipp Wrann

**Comment by NamelessCoder** [comment]
Hi Philipp,

No ports are currently being considered, mostly because every custom integration you can do (which includes ViewHelpers, also those shipped with Fluid) requires PHP. The internal mechanics of Fluid would, I assume, also be exceptionally difficult to implement in the current state (JS objects being so different in nature from PHP ones).

Fluid also has heavy dependency on access to a filesystem that allows listing etc. (that's not relevant for an node app, I know, but it does mean such a port would never work client-side without significantly diverging from the "upstream" version).

One thing is being done, though - hopefully I will succeed in creating a lexer for Fluid. That lexer would be very simple to port to any language, which would give an app at least a very low-level way to understand Fluid templates (e.g. tokenise them, detect f:render, detect layout name, detect variables used, and more). It would not be capable of doing any rendering, but you could easily use it for example to rewrite templates.

There's a bit more info about this on https://gist.github.com/NamelessCoder/a81e1682eae7ba148a756bdd5b74a473

So, from my perspective, I would not port Fluid as such - but I would not have any hesitation in porting the *lexer* part of Fluid to any language. At its core, a lexer is just a big `switch` statement inside a loop and the most advanced thing it does is to operate on arrays (popping, adding, counting, end'ing, etc.). The rest is conditions to perform character analysis and switch capture states.

A lexer could also more easily be reduced further to a BNF which can then be used to generate a lexer for nearly any language. I myself didn't start from BNF (and then generate a PHP lexer) because I like to completely control the lexer and determine the capabilities, and *then* declare the syntax and grammar (for example as BNF).

But porting the full feature set, or just the majority of it, to another language... no, I would not attempt that. Especially not a traditionally client-side language - I'd be more inclined to port it to something like C++ but it's still an absolutely huge task.
