### ISSUE TITLE
Feature Request: format.crop ViewHelper

### ISSUE THREAD

**Issue by pixelbrackets** [TYPO3/Fluid#381]
I miss a basic ViewHelper to crop a text. Like [f:format.crop](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/Format/CropViewHelper.php).

PS: Are such format Viewhelpers not included on purpose, or just not converted into a standalone version yet?

**Comment by mbrodala** [comment]
The current implementation of that viewhelper depends on TYPO3 internals, that's why it has not been ported yet. Porting it would mean at least copying the TYPO3 implementation which is rather huge IMO.

**Comment by NamelessCoder** [comment]
I'm afraid this isn't going to happen. While such a formatter may be added in separate ViewHelper packages (like whichever standalone package becomes the base for VHS at some point) it won't be included in Fluid itself simply due to the size of the implementation and the rabbit-hole nature of adding more and more such formatters.

If we don't draw the line at absolute bare minimals, we'd be adding hundreds of conceivable formatters (and implicitly, agreeing to maintain them). Besides, Fluid is very much designed to let anyone provide such extended capabilities as third party code so we don't follow the same "everything must be in the box" approach the main TYPO3 product does. Think of Fluid as an engine and things like `f:format.crop` in TYPO3 as implementations building on that engine.

**Comment by pixelbrackets** [comment]
Sounds absolutely reasonable. Thanks for the explanation.
