### ISSUE TITLE
{parsing off} results in numerous output

### ISSUE THREAD

**Issue by pniederlag** [TYPO3/Fluid#392]
I do have a Plugin with one controller and one action. There is one corresponding Fluid-Template associated with the Plugin.

If I add a {parsing off} instruction in the template it will be rendered three(!) times in the output of the page.

One time in the &lt;head> section, one time in the slot where the plugin is assigned and one time right before the closing &lt;body> section.

**Comment by sascha-egerer** [comment]
You are talking about Fluid in TYPO3, right?
I don't think that has really something to do with the parsing off option. Could you please add some more related info or maybe just add a minimal example extension how to reproduce the issue?

**Comment by pniederlag** [comment]
Here you go, a simple extension that triggers the problem. I do have EXT:themes plus EXT:autoloader enabled(autoloader NOT enabled for this extension).

Would be nice to know wether you can reproduce the problem or not (typo3/cms  v8.7.13).

[fluid_parsing_off.zip](https://github.com/TYPO3/Fluid/files/2165143/fluid_parsing_off.zip)

**Comment by mbrodala** [comment]
It sounds like this could be related to the automatic rendering of header and footer assets.

**Comment by sascha-egerer** [comment]
Thank you for the example. 
I can reproduce the issue. The issue only occurs if `{parsing off}` is used in a template file. If you use it in a partial everything looks fine. 
Not sure if that issue is related to fluid or if it is a bug in the implementation of TYPO3

**Comment by pniederlag** [comment]
I can confirm that overriding public function renderAssetsForRequest() {} does solve the problem. So it seems Mathias is quite right with his assumption.

https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.6/Feature-79409-AutorenderAssetSectionsInFluidTemplateWithController.html

btw. wasn't aware of that feature until now, nice one :->

**Comment by sascha-egerer** [comment]
Ok, cool. Could you please create a new issue in the TYPO3 bug tracker and close the issue here?

**Comment by pniederlag** [comment]
as overriding the methode seems a valid approach and due to the fact that I don't have an idea on how to tackle the problem in a better way I ditched it to https://forge.typo3.org/issues/85484.

Thx for your feedback und good work!

CU,
Peter

**Comment by NamelessCoder** [comment]
Just a side note: `{parsing off}` used in a template is the same as doing `$content = str_replace('{parsing off}', '', file_get_contents($myTemplateFile));` because no calls to `f:render` or designations of `f:layout` will be active. So it is definitely reserved for Partials or special cases where one might render a template with Fluid but sometimes feed it non-Fluid source.

But the conclusion is that using this modifier disables the parsing which means the template is no longer a Fluid template, technically. Which in turn means that implementations which require a Fluid template (such as the automatic rendering of header/footer asset sections) may not work if you intentionally disable Fluid.
