### ISSUE TITLE
Feature: slots

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/Fluid#427]
The `contentAs` argument provided by Fluid is very useful to pass arbitrary content as variable to a partial/section.

However, this is limited to a single variable, if multiple pieces of content should be passed, one has to e.g. resort to doing inline `f:render` calls within `arguments` instead.

A nice solution to this would be a system similar to [Vue.js component slots](https://vuejs.org/v2/guide/components-slots.html).

### Basic example

`Example.html` template:

```html
<f:render partial="Foo" arguments="{as: 'usual'}">
Some content with<f:if condition="{lie}">out</f:if> regular Fluid.
</f:render>
```

`Foo.html` partial:

```html
Just the {as}:
<f:slot/>
```

### Named slots example

`Example.html` template:

```html
<f:render partial="BaseLayout">
  <f:template slot="header">
    <h1>Here might be a page title</h1>
  </f:template>

  <p>A paragraph for the main content.</p>
  <p>And another one.</p>

  <f:template slot="footer">
    <p>Here's some contact info</p>
  </f:template>
</f:render>
```

`BaseLayout.html` partial:

```html
<div class="container">
  <header>
    <f:slot name="header"/>
  </header>
  <main>
    <!-- Slot without name renders the content not encapsulated in `f:template` -->
    <f:slot/>
  </main>
  <footer>
    <f:slot name="footer"/>
  </footer>
</div>
```

If we stick to the same naming or use something like `argument` is up to discussion of course as is this feature in general.

**Comment by NamelessCoder** [comment]
Perhaps easier implemented and understood if using `f:variable` - hypothetical and unsupported currently:

```xml
<f:render partial="Something">
   <f:variable name="arg1">Special value for arg1 variable</f:variable>
   <f:variable name="arg2">Special value for arg2 variable</f:variable>
</f:render>
```

The result being that in addition to, or instead of, assigning these variables only when rendering the content and then clearing them before actually rendering the partial or whatnot - _the variables would be redirected to be collected as arguments for calling the partial_.

This could be implemented with very little effort (toggle set in ViewHelperVariableContainer by `f:render` and respected by `f:variable` then extracting variables before sub-rendering) and has the benefit that it only uses already supported features but makes them work slightly different when used in `f:render`.

Bonus: it becomes *excessively* easy to declare long-winded, non-inline, HTML-carrying, not-escaped variables this way since this would work regardless of `contentAs` and for any type of render statement as a means to expand arguments.

Bonus-bonus: we avoid known issues with recursive regexp in huge inline array expressions.

**Comment by NamelessCoder** [comment]
PoC coming right up, actually.

**Comment by sascha-egerer** [comment]
I've added an implementation for Fluid 3.
