### ISSUE TITLE
Documentation: If-ViewHelper

### ISSUE THREAD

**Issue by dax-jones** [TYPO3/Fluid#442]
About rendered [If-ViewHelper](https://docs.typo3.org/typo3cms/ViewHelperReference/latest/typo3fluid/fluid/latest/If.html) in official documentation:

There are some issues with the if ViewHelper:

* The weird formatting makes it really hard to read
* It seems the alternative to use comparing arrays instead of strings is no longer necessary, see my related question on [StackOverflow](https://stackoverflow.com/questions/55222615/how-to-compare-a-string-with-a-variable-in-typo3-fluid). 
* "As a condition is a boolean value, you can just use a boolean argument" : a little vague

**Comment by NamelessCoder** [comment]
Hi @dax-jones - welcome to GitHub, looks like you created an account just to report this issue so that's appreciated!

About your points:

* The formatting is being taken care of but isn't within the context of Fluid itself. The documentation is rendered by a combination of a package I built and an extended feature for that package which generates RST. Both this, and the documentation it extracts, is being improved formatting-wise.
* You're completely right! Comparison of arrays as example should be removed and substituted for some examples that use `&&` etc.
* Wording is a bit weird here but what's implied is that you can pass a variable that's a boolean instead of writing the expression like `<f:if condition="{myBool} > 0">` because the expression doesn't actually need to be an actual expression if it's already a (boolean-compatible) value.

I'll leave this issue open as a reminder to update the doc of this ViewHelper.

**Comment by lolli42** [comment]
Hey.

We've had quite a few changes to the VH docs meanwhile, some patches referenced by Claus here. I hope the overall documentation and documentation rendering is better now. I'll close the issue for now. If there is anything specific left to do, let us sort that out with fresh issues.
