### ISSUE TITLE
Method textAndShorthandSyntaxHandler dies with PHP 7.3.5

### ISSUE THREAD

**Issue by thomashohn** [TYPO3/Fluid#453]
The method  textAndShorthandSyntaxHandler dies with PHP 7.3.5 due to a change in the behaviour of preg_split - if it returns false it should pass through the text instead

**Comment by mstaatz** [comment]
For me i have this issue "throwExceptionsForUnhandledNamespaces" in vendor/typo3fluid/fluid/src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

and also with "textAndShorthandSyntaxHandler" in vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php

there are a lot usecases like this:

**Comment by mstaatz** [comment]
for me i have this issue "throwExceptionsForUnhandledNamespaces" in vendor/typo3fluid/fluid/src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

and also with "textAndShorthandSyntaxHandler" in vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php

there are a lot usecases like this:
`$sections = preg_split(Patterns::$SPLIT_PATTERN_SHORTHANDSYNTAX, $text, -1, PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY);`

`foreach ($sections as $section) {`

this result in many error for the case that preg_split returns "false". foreach will not work with "false"

but this is an other thing

it seems PHP 7.3 uses a newer PCRE Library Version and it will not work the same way

i could fix this after debugging with:
`var_dump(array_flip(get_defined_constants(true)['pcre'])[preg_last_error()]);`

and set the backtrack_limit to a higher value:
`ini_set('pcre.backtrack_limit', 10000000000);`

there is a default of 1000000 .... checked this value on PHP 7.2.18 and 7.3.5

as i am not an Expert with RegEx i could not say what is going wrong .... this are only the results of my debugging

**Comment by jonakieling** [comment]
Hi there,

we have stumbled upon the same issue and checked the template part that was causing it.
In our case we have inline Javascript which leads to the preg_split not finishing.

```
                    <div id="div-with-identation">
                        <script type="text/javascript">
                            function this_is_problematic(some_arg) {
                                # breaks because of the non-matching hashtag
                                # resulting in backtracking
				# backtracking gets catastrophic because of all the whitespaces
                                # at the start of the first line with the hashtag
                            };
                        </script>
                    </div>
```

It causes Catastrophic Backtracking like described here: https://www.regular-expressions.info/catastrophic.html
You can try it out here: https://regex101.com/r/P4mlnc/1

There are a few answers to similar issues with regex over at stack overflow.
https://stackoverflow.com/questions/9687596/slow-regex-performance/9687739#9687739

I'll report back, if we have found a fix for the regex.

In the meantime the fix for our template was to put the Javascript part in a separate partial with the `{parsing off}` directive at the top of the file. Variables are defined outside the partial since the scope only matters in the generated html.

Kind regards,
jona

**Comment by YetiCGN** [comment]
I have stumbled upon the same when updating my local machine to PHP 7.3. If you could pull my fork and test it, tell me if that fixes it for you?

**Comment by liayn** [comment]
I could fix this by simply wrapping the offending inline JS stuff in the Fluid template with
```
<![CDATA[ ... ]]>
```

**Comment by liayn** [comment]
Nonetheless #460 should be merged as it is generally bad practice not to handle error conditions.

**Comment by liayn** [comment]
https://review.typo3.org/c/Packages/TYPO3.CMS/+/61119

**Comment by NamelessCoder** [comment]
Solved by https://github.com/TYPO3/Fluid/commit/865890c3cffaf8d5f6aa44295d42a84a103895ec and https://github.com/TYPO3/Fluid/commit/2d2d5db7268f57b9f8e83e0d3c474f7603b54cab.
