### ISSUE TITLE
LazyLoadingProxy not supported during rendering

### ISSUE THREAD

**Issue by ohader** [TYPO3/Fluid#468]
`LazyLoadingProxy` of Extbase is not supported during variable extraction and rendering.

`LazyLoadingProxy` provides magic methods (`__call` and `__get`) which would trigger loading the surrogated and actual instance. However, Fluid's variable accessor is not capable of dealing with that yet:

```
    protected function canExtractWithAccessor($subject, $propertyName, $accessor)
    {
        $class = is_object($subject) ? get_class($subject) : false;
        if ($accessor === self::ACCESSOR_ARRAY) {
            return (is_array($subject) || ($subject instanceof \ArrayAccess && $subject->offsetExists($propertyName)));
        } elseif ($accessor === self::ACCESSOR_GETTER) {
            return ($class !== false && method_exists($subject, 'get' . ucfirst($propertyName)));
        } elseif ($accessor === self::ACCESSOR_ASSERTER) {
            return ($class !== false && $this->isExtractableThroughAsserter($subject, $propertyName));
        } elseif ($accessor === self::ACCESSOR_PUBLICPROPERTY) {
            return ($class !== false && property_exists($subject, $propertyName));
        }
        return false;
    }
```

It's obvious that Fluid should not be bound to ORM specifics of Extbase and be decoupled. However, Fluid should provide an interface that "annotates" ORM models (properties) in order to retrieve data - or to still keep it simple (however, without being explicit) just check against `__call`and `__get` magic methods.

**Comment by mbrodala** [comment]
Can you retry with the latest master?

There where a few changes to support objects with magic getters (91d8b887817597ea2e46c1a10b073a2c1573a80a and d8ccbcddc5c01ad3e6d9e74d3ddab919f8a44f20)

**Comment by ohader** [comment]
Thanks for pointing this out. I was using TYPO3 v9 and Fluid v2.6.1 which probably did not support that yet. I'll check that soonish...

**Comment by NamelessCoder** [comment]
In light of https://github.com/TYPO3/Fluid/pull/489 I would reconsider the choice to support overloaded methods - it seems to invariably lead to high complexity, bad performance or both. And it is definitely not the most common use case.

One way to achieve support for (single) lazy properties in Extbase models used in Fluid, is to make the getter method of the parent object check if internal instance is still a lazy-loading proxy and if so, trigger it before returning.

If you do not wish to change the default getter (which could have an impact on other use cases, making them less efficient) it is also possible to implement a virtual getter, e.g. `{object.thawedSingleLazy}` and `public function getThawedSingleLazy()` since Fluid does not require that the internal property actually exists.

My choice would be to keep Fluid relatively naive about what an object looks like internally, yet do a minimum to guarantee that "call to undefined function" does not happen. And that essentially means keeping the 2.6.1 behavior for the foreseeable future.

**Comment by NamelessCoder** [comment]
Closing; magic method support has been rolled back and will not be re-attempted since it is only possible to make remotely consistent by use of Reflection which violates PHP's visibility restrictions.

A valuable lesson learned - with big thanks to all participants in the various issues/pull requests!
