### ISSUE TITLE
Support for overloaded methods breaks property access of instances with magical __call

### ISSUE THREAD

**Issue by benwick** [TYPO3/Fluid#479]
This commit is very problematic: https://github.com/TYPO3/Fluid/commit/d8ccbcddc5c01ad3e6d9e74d3ddab919f8a44f20

It changed the test for a getter accessor from `method_exists` to `is_callable`. The problem is: `is_callable` returns always `true` for class instances with a magical `__call` method. So, if you try to access a public property of a class instance with `_call`, it will always fail trying to access the value with a getter method...

Example: In some DCE templates I access properties from the TyposcriptFrontendController like this: `{TSFE.metaCharset}`.

The result is this: 
![image](https://user-images.githubusercontent.com/2118579/65696945-6bc1b680-e07a-11e9-945f-fba8d5bfe682.png)

**Comment by benwick** [comment]
One solution could be: Make this condition (https://github.com/TYPO3/Fluid/blob/master/src/Core/Variables/StandardVariableProvider.php#L353) the first one instead of the last...

**Comment by NamelessCoder** [comment]
Hi @benwick,

The reason for having the "can we call a getter?" check first:

* Historically, the main data source for Fluid templates has been model objects with getters.
* Which use getter methods to extract values.
* Which is why this check is done first.

The second check is for array access since this is the second-most frequent way a variable can be extracted. Last comes the property check, since this is the least frequent use case (and on a side note, TYPO3 CMS is moving away from these).

Moving the condition for public property to the top means we break another use case - if a getter method exists and a public property exists which both match the name, we would be changing that priority.

Another way could be to add an additional check here: https://github.com/TYPO3/Fluid/blob/master/src/Core/Variables/StandardVariableProvider.php#L347 to check `&& !property_exists($subject, $propertyName)` so a (virtual) getter method will not be called if a public property exists. I suppose we can live with one additional function call although it adds it the most frequent use case.

(PS: overloading is, generally speaking, bad practice - as far as possible you should not use it as a solution in your own code!)

**Comment by NamelessCoder** [comment]
Looks like we can't even do `!property_exists()` since this doesn't respect accessibility. In any case, it would be best if we can come up with a solution that doesn't change priority of current checks.
