### ISSUE TITLE
Strategy for streaming rendered result

### ISSUE THREAD

**Issue by stephanschuler** [TYPO3/Fluid#502]
Hey there!

I'm currently creating a really huge XML file via CLI.
The result is 500MB with lots of whitespaces for indentation, at least 300MB with no whitespaces.

I came across the idea of not creating a huge string as result but to use PHP stream resources for that. Would be awesome if I could just `$view->renderToStream(fopen('/tmp/whatever-file.xml'))`.

If the target is a file path anyway, rendering could just directly output to that very file.
If I wanted to use PHP memory, I could use `fopen('php://memory')` as target.
If I wanted to use PHP memory in the first place but swap if necessary, I could use `fopen('php://temp')`.

The reasoning is basically equivalent to the PSR-7 StreamInterface.

I do realize this would be a huge change for both, API as well as inner workings. And I wouldn't be surprise  if you considered this too huge with too little target audience.

Here's a little something I put together to work around that:
https://github.com/stephanschuler/fluid-stream-buffer

Please notice: I didn't add code to fluid itself but only created view helpers that added content to a side channel instead of passing it to the output. So this implementation is *not* what I suggest here.

An actual implementation within the scope of fluid could and should make use of the PSR-7 StreamInterface whenever rendering is passed on from one node to its child nodes.

Of course some ViewHelpers will accumulate all child rendering and post process it in a single step. If I'm creating a HashViewHelper , there's of course no easy way to do this on a stream without reimplementing md5 or sha1. But to my experience, the majority of "nodes" in general will create their content iteratively (f:for, f:render, regular XML/HTML) and might be a good fit for streaming results.

It should be the responsibility of the child node to decide whether to create a new output stream to work on, be added to the parent stream at the end and be passed that along to respective child nodes or to directly work within the stream of the parent. The later would basically be equivalent to the current state of fluid where each ViewHelper holds its own content until it returns it entirely. The first would be the improvement because a ViewHelper now can pass even partial result directly upstream, best case all the way up to the file system.

What do you think?

Regards
Stephan.

**Comment by NamelessCoder** [comment]
Hi @stephanschuler,

Interesting use case (although it is kind of rare).

The main problem I see is this: _when evaluating a node it is not known if the output is truly output or an input for another node_. Whereas this is somewhat easy to determine if the node exists as an argument (in which case it's never output, it's always consumed), it gets much more difficult (impossible, as far as I can tell) to determine if a node used as child of another node, produces output or gets consumed.

The good thing about your VH solution is that it requires the person who writes the template to make these decisions - and then explicitly opt-in to output via stream in places where this is known to be possible (e.g. a loop which outputs XML tags for each iteration).

> But to my experience, the majority of "nodes" in general will create their content iteratively (f:for, f:render, regular XML/HTML) and might be a good fit for streaming results.

Unfortunately this logic depends on usage, not on node type. It cannot be clearly deliniated that, for example, `f:for` always produces output and does not get consumed by an enclosing ViewHelper. While it is true for most common usages that a ViewHelper like `f:for` will produce output, there is no universal rule that it *always* will produce output and never be consumed.

> It should be the responsibility of the child node to decide whether to create a new output stream to work on, be added to the parent stream at the end and be passed that along to respective child nodes or to directly work within the stream of the parent

I do not agree here: it is actually the *parent* node's responsibility to determine how a *child* should be processed, since it is the parent which may either consume or output a child node - and this further points to your current solution being the right one (since in that solution, you're explicitly adding a special type of parent node that streams the child nodes' output as opposed to collecting and returning it).

The problem of delegating this decision to any given child node is that if this child node is used within a ViewHelper that outputs vs a ViewHelper that consumes it, is that the child node is not aware of the parent (in other ways than through transferred contexts like ViewHelperVariableContainer) and thus cannot make the decision if the *parent* needs output or allows streaming.

If necessary I can provide examples of ambiguous usages (consume vs output) but I suspect you completely understand it without examples given the nicely technical aspects of the solution you made!

In the end I'd welcome a package that provides streaming ability through ViewHelpers, and would happily consider adding such ViewHelpers to Fluid itself (if sufficiently mature and wanted by users). But I cannot see a sensible way to integrate this in Fluid itself. Literally all node types in Fluid can be used either to produce output or consume child nodes, entirely depending on context (the structure of the Fluid template, specifically structure of all parent nodes).

If all nodes were capable of producing to streams then any node that may be used as a parent node would need to control this in detail - which then results in significant complexity and performance drain due to I/O. So a custom node type (a ViewHelper) is the right solution.

**Comment by NamelessCoder** [comment]
I do have some hints for improving your solution:

* You could store the stream's handle in ViewHelperVariableContainer instead of creating it with a ViewHelper, this gives better separation of the layers and makes one of the ViewHelpers redundant.
* And make your ViewHelper return normally in case the stream handle isn't set, which makes the `into` parameter redundant.
* This then allows you to render the template as normal, or to stream, depending on how you initialized your ViewHelperVariableContainer.

The resulting code would then look more like:

```xml
  
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns:f="http://typo3.org/ns/TYPO3Fluid/Fluid/ViewHelpers"
       xmlns:s="http://typo3.org/ns/StephanSchuler/FluidStreamBuffer/ViewHelpers"
>
        <f:for each="{items}" as="item">
            <!-- each iteration produces to stream if stream is provided in context -->
            <s:stream>
                <item id="item-{item.id}">
                    <name>{item.name}</name>
                    <id>{item.id}</id>
                    <f:for each="{item.attributes}" key="key" as="value">
                        <attr name="{key}">{value}</attr>
                    </f:for>
                </item>
            </s:stream>
        </f:for>
</items>
```

**Comment by NamelessCoder** [comment]
By the way, Fluid 3.0 will make it possible to create an even smoother integration of your use case. There are two important facts to know:

* Fluid 3.0 discards template compiling and static rendering
* And it will always provide you with the raw child nodes

This means that your ViewHelper could recursively iterate through children and children of children, along the way substituting each ViewHelper that you *know* for a fact produces output, like `f:for` in your example. This way you could "scan" for all occurrences of a particular ViewHelper and replace its child nodes with a "streamable" node that streams each child node's output (the equivalent of manually having to use `s:stream` around streamable blocks, but requiring only one node at the root level).

This is just to say that Fluid 3.0 facilitates some advanced manipulation of nodes that Fluid 2.x can only do with parse-time methods and/or node interception. And that this would be perfect for your use case!

**Comment by lolli42** [comment]
Hey. I hope it's ok to close here for now: Implementing streams in Fluid directly has quite same impact on the API (as already mentioned), and is currently not a target of current development.

I agree this may be beneficial when dealing with huge amounts of generated content, but this is a relatively seldom use case when Fluid is mostly meant to be used for "casual" html output.

It's possible this can be picked up later again, but for now, we'll close here and wait for contributors actively working on this.
