### ISSUE TITLE
Leading zero gets truncated in attributes for input view helper.

### ISSUE THREAD

**Issue by jonakieling** [TYPO3/Fluid#521]
Hi everyone,

for a form I needed an input for a zip code with a pre-filled input of type text. Fluid is used in Version 2.6.9 with TYPO3 10.4.5

`<f:form.textfield property="zip" value="06108" />`

The browser only shows 6108 and the generated cache file also has lost the leading zero. I checked the TYPO3 view helper side of things and the value seems to already been initialized without the zero. I did not dig into fluid core for this just yet.

Appreciate any help or hints :) 

Kind regards,
Jona

**Comment by NamelessCoder** [comment]
Hi Jona,

First of all: this shouldn't be a problem with Fluid 3.0 which doesn't make a different decision based on the nature of node values (numeric or not) - but it does make a difference on Fluid 2.x.

I believe the problem lies in the way node values are analysed when parsing the template. Fluid 2.x will check the node's value and look for a numeric value and detects zero-prefixed values as numerical. It then casts the value (by math operation adding a `0` to the value, e.g. `$value += 0` which preserves the type float/int). This means that when rendering the value, the leading zeroes are not rendered since the value was converted to an `int` before being output.

I think the best I can do is provide you with a workaround for this case. What you can do is insert the initial value of the input field as a template variable (type string) and then use that template variable instead of the hardcoded text:

`<f:form.textfield property="zip" value="{defaultZip}" />`

This would cause Fluid to create an ObjectAccessorNode which reads the value from the VariableProvider - and it avoids the casting operation (the node is no longer a NumericNode, and values from ObjectAccessorNode are output without casting).

Unfortunately we can't change this casting operation since this constitutes a breaking change, meaning it would only be possible to include in the next major version, which would be version 3 - and this version already has avoided this problem by dropping the NumericNode.

It *might* also be a good idea to do a test round on your site if it supports Fluid 3.0. This can for example be done by temporarily aliasing the Fluid composer dependency:

`composer req typo3fluid/fluid:^3 as 2.6.99`

Depending on which third party ViewHelpers you use (the ViewHelpers from TYPO3 CMS are considered third party in this case, but all of them are updated to work with Fluid 3.0) this could solve the problem without the need for the workaround above - and also brings several other benefits, for example increased performance, one fewer caches to consider and many new template syntax abilities such as ECMA array syntax support. If nothing else I would say it is worth a try!

**Comment by jonakieling** [comment]
Thanks for the detailed explanation! Using a variable for the default works like a charm and is less invasive in this case.
