### ISSUE TITLE
Providing original node src via RenderingContext

### ISSUE THREAD

**Issue by MajPay** [TYPO3/Fluid#557]
See: https://stackoverflow.com/questions/68741313/is-it-possible-to-render-raw-fluid-markup-without-evaluating-it/68746142#68746142

I wanted to develop a showcase with components that developers can use as a reference to copy snippets from. Doing so it would be practical if you could access the original fluid src (not parsed) from your viewhelper.

This could also provide better debugging options.

A possible solution could be to set a public property in the rendering-context, that contains the current node fluid src. In Production mode this could be set to null, but in development context or if the feature is enabled, it could return the raw fluid markup.

The rendered template would need to have an additional call before every ViewHelper invocation. In Production-Mode it would not be added and therefore not effect the performance.

An example of the rendered template:

```php
// ...
$output0 .= '
    <div class="some-html-markup">
        <h5>Headline</h5>
        <div class="more-markup">
            <a href="">
                ';
// Rendering ViewHelper TYPO3Fluid\Fluid\ViewHelpers\Format\RawViewHelper
/* NEW */
$currentNodeOriginalSource = <<<SRC
<f:someViewHelper />
SRC;
$renderingContext->setCurrentNodeOriginalSource($currentNodeOriginalSource);
$renderChildrenClosure2 = function() use ($renderingContext, $self) {
$output3 = '';
};
/* NEW END */
// ...
```

Alternatively instead of the markup added as string, the reference could be set (for example in this format):
$currentNodeOriginalSource = 'path/to/file:13:15-14:0';

Saying: in path/to/file from line 13, chr 15 to line 14, chr 0 you can find the original fluid source.

As a theme-provider / extension-provider i could access the src property in the renderingContext and do my custom stuff with it. For example running htmlspecialchars on it and rendering it as a code-example above the rendered fluid output... 

I would love such a feature.

**Comment by MajPay** [comment]
Is it possible there existed a concept for something like this?

I could find a reference to a "ChildNodeAccessInterface" in typo3fluid src

```
     * If the view helper implements \TYPO3Fluid\Fluid\Core\ViewHelper\ChildNodeAccessInterface,
     * it calls setChildNodes(array childNodes) on the view helper.
```

Such an interface does not exist though

**Comment by NamelessCoder** [comment]
I've replied to the question on StackOverflow for added visibility: https://stackoverflow.com/a/68763286/2162619

In short: this is possible in Fluid 3.0 but is not possible in Fluid 2.x and earlier and will not be added as a feature in 2.x since it would drastically increase memory usage and size of compiled templates and only serves an extremely rare use case.

Re: ChildNodeAccessInterface, it is true that the interface no longer exists - but this is because `setChildNodes` is always called on every ViewHelper (and is by the way also available from `$this->viewHelperNode`). The argument value consists of an array of already parsed nodes such, e.g. instances of TextNode, ViewHelperNode - and the child nodes array only exists *before the template is compiled*. The purpose of this is to allow a ViewHelper to implement a custom `compile()` method that processes child nodes in various ways, see for example AbstractConditionViewHelper and SwitchViewHelper (though these ViewHelpers access the child nodes through the ViewHelperNode that is passed to the `compile()` method). It would in other words not facilitate the use case you describe, it has a completely different purpose.

**Comment by lolli42** [comment]
Hey. I hope it's fine to close here: As Claus outlined, this is problematic in fluid v2 and probably expensive performance and memory wise. We probably won't do this in fluid v2. v3 is currently stalled and it does not make much sense to keep the issue open for this purpose at the moment.
