### ISSUE TITLE
Switch to static functions in closures

### ISSUE THREAD

**Issue by IndyIndyIndy** [TYPO3/Fluid#701]
Another little optimization, that can be done. From what I see, none of the closure functions use $this,

**Comment by lolli42** [comment]
Hey.

I don't think we can do this at the moment. The compiled template code currently creates tons of closures, and some of them aren't needed at all, or could be substituted with a more simple `static fn () => '';`. We'll have disentangle the code generation further to really use that. See also my current headaches with if VH in https://github.com/TYPO3/Fluid/issues/771 and https://github.com/TYPO3/Fluid/issues/769

I'll close here for now since the PR won't make it as such.
