### ISSUE TITLE
Fluid 2.9.x has trouble with StaticCacheable ViewHelpers and cached partials/templates

### ISSUE THREAD

**Issue by bmack** [TYPO3/Fluid#804]
When working with EXT:solr (dev-main) we've noticed a strange behaviour which I want to demonstrate quickly.

I have
* A template file (Results.html)
* Calling a partial file (Pagination.html)
* Using a simple ViewHelper (static cacheable) that just returns the given argument "page".

When calling the page with the template + partial for the first time, everything is fine, the second time (when Partials and Templates are cached), the ViewHelper always outputs the same value.

This does not happen in 2.8.x but only in 2.9.x.

Results.html:
```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	xmlns:s="http://typo3.org/ns/ApacheSolrForTypo3/Solr/ViewHelpers"
	data-namespace-typo3-fluid="true"
>

<f:render partial="Result/Pagination" arguments="{allPageNumbers: '{1:1, 2:2, 3:3, 4:4, 5:5}', previousPageNumber: 1, nextPageNumber: 3}"/>

</html>
```

Pagination.html:
```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
	xmlns:f="http://typo3.org/ns/TYPO3/Fluid/ViewHelpers"
	xmlns:s="http://typo3.org/ns/ApacheSolrForTypo3/Solr/ViewHelpers"
	data-namespace-typo3-fluid="true"
>

<ul class="pagination-test">
	<li class="page-item">{s:compilable(page: previousPageNumber)}- {previousPageNumber}</li>

	<f:for each="{allPageNumbers}" as="page">
		<li class="page-item">{s:compilable(page: '{page}')} - {page}</li>
	</f:for>

	<li class="page-item">{s:compilable(page: '{nextPageNumber}')} - {nextPageNumber}</li>
</ul>

</html>
```

CompilableViewHelper.php:
```
<?php
declare(strict_types=1);

namespace ApacheSolrForTypo3\Solr\ViewHelpers;

use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\Core\ViewHelper\Traits\CompileWithRenderStatic;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;

class CompilableViewHelper extends AbstractViewHelper
{
    use CompileWithRenderStatic;

    /**
     * @inheritdoc
     */
    public function initializeArguments(): void
    {
        parent::initializeArguments();
        $this->registerArgument('page', 'int', 'The page', false);
    }

    public static function renderStatic(
        array $arguments,
        \Closure $renderChildrenClosure,
        RenderingContextInterface $renderingContext,
    ) {
        $page = $arguments['page'] ?? 1;
        return (string)$page;
    }
}
```

The output on the first run:
```
<ul class="pagination-test">
<li class="page-item">1- 1</li>
	<li class="page-item">1 - 1</li>
	<li class="page-item">2 - 2</li>
	<li class="page-item">3 - 3</li>
	<li class="page-item">4 - 4</li>
	<li class="page-item">5 - 5</li>
<li class="page-item">3 - 3</li>
</ul>
```

The output on all subsequent runs:
```
<ul class="pagination-test">
<li class="page-item">3- 1</li>
	<li class="page-item">3 - 1</li>
	<li class="page-item">3 - 2</li>
	<li class="page-item">3 - 3</li>
	<li class="page-item">3 - 4</li>
	<li class="page-item">3 - 5</li>
<li class="page-item">3 - 3</li>
</ul>
```

**Comment by s2b** [comment]
Unfortunately, I wasn't able to reproduce this. At first I tried additional functional test cases, which were all green. Then I created a small demo extension and installed it in a TYPO3 v12 instance with Fluid 2.9.1 and default caching in files: It worked both for the first and all subsequent requests. I also checked that the cache file was actually used.

Could you try it again in your environment with the demo extension?

https://github.com/s2b/fluidbug

Output in my environment:

```xml
<ul class="pagination-test">
    <li class="page-item">1- 1</li>

    
        <li class="page-item">1 - 1</li>
    
        <li class="page-item">2 - 2</li>
    
        <li class="page-item">3 - 3</li>
    
        <li class="page-item">4 - 4</li>
    
        <li class="page-item">5 - 5</li>
    

    <li class="page-item">3 - 3</li>
</ul>
```

**Comment by sbuerk** [comment]
It's not possible to reproduce this in a fluid functional test,
nor using the ext provided by @s2b in core monorepo main + 12.

After chatting with Benni, he mentioned the solr example ddev.
Checked it there. The solr ViewHelper showed that behaviour as
described in the issue. The fluidbug extensions activated in the
solr ddev still not reproduced this state.

Standing and looking on the Services.yaml of the the extension for
the solr viewhelper, as it pointed to that exact viewhelper - Benni
jumped in and had a look to.

The viewhelper are loaded over Services.yaml, but not declared as
`shared: false`. Adding this to the extension viewhelper it solved
the issue.

It's still curious, why this worked with fluid 2.8.0 but not with 2.9.1.
Maybe the gathered information can help us to find something related.

**Comment by s2b** [comment]
And you‘re sure that it is related to the fluid version and not changes in SYSEXT:fluid? I‘m thinking about this change:

https://review.typo3.org/c/Packages/TYPO3.CMS/+/78917

**Comment by bmack** [comment]
Culprit is https://github.com/TYPO3/Fluid/commit/1f1dc5ac2d23aff659a8b305f0ac765d15b7fba7

**Comment by sbuerk** [comment]
I was able to create functional with mimic a "DI Aware" ViewHelperResolver simulating
with the ViewHelper beeing "configured" as "shared: true" in a DI (like TYPO3).
I'm using a simple `ViewHelperResolver` mock extend as we do not have DI in FLUID.

See the commit on the branch: https://github.com/TYPO3/Fluid/tree/issue-804

I wanted to added a cross check without a shared viewhelper, but curiosly the shared viewhelper test then going green ! So that 's another issue. Therefore, I skip the
non-shared viewhelper test in on the branch/commit for now.

Benni `bisect` that yesterday in the ddev solr test project where it was reproducable.
I've done the git bisect know directly in fluid with the functional test on the branch
with the same result:

```
1f1dc5ac2d23aff659a8b305f0ac765d15b7fba7 is the first bad commit
commit 1f1dc5ac2d23aff659a8b305f0ac765d15b7fba7
Author: Christian Kuhn <lolli@schwarzbu.ch>
Date:   Sat May 13 16:11:21 2023 +0200

    [TASK] Move convert code from ViewHelperNode to VH (#787)
```

In my eyes, shared viewhelpers should be "possible" .. make sense for Viewhelpers
using the `CompileWithRenderStatic` anyway. 

I starred on the commit/change but cannot explain from reading why this changes the
behaviour that drastically. (The test issue on the otherhand is also curious).

Need some break now, but next round would be to debug that what in this change leads
to that effect.

@s2b The core change https://review.typo3.org/c/Packages/TYPO3.CMS/+/78917 basically allows to instiantiate ViewHelpers not coverd by DI (shared or non shared). Therefore, not the issue. Which is ensured as we can reproduce this in fluid which does not uses the core and core implementation at all.
