### ISSUE TITLE
Feature Request: Make public properties of classes accessible.

### ISSUE THREAD

**Issue by ervaude** [TYPO3/Fluid#865]
This feature request is about accessing class properties in fluid via

```HTML
{foo.bar}
```

Currently, fluid needs a "getter" method (getProperty, hasProperty, isProperty, etc) to access class properties even if the properties are public:

```PHP
class Foo
{
	public function __construct(public readonly string $bar) {}

	// getter for fluid
	public function getBar(): string
	{
		return $this->bar;
	}
}
```

If we could access public properties **directly**, we could get rid of the getter methods:

```PHP
class Foo
{
	public function __construct(public readonly string $bar) {}
}
```

Thanks for looking into this!
Cheers

**Comment by mbrodala** [comment]
Actually this works just fine since ever. What is your specific issue?

See:

- https://github.com/TYPO3/Fluid/blob/736101a166f257b1e60de2f1e0253bf77d0d1f9a/src/Core/Variables/StandardVariableProvider.php#L159
- https://github.com/TYPO3/Fluid/blob/736101a166f257b1e60de2f1e0253bf77d0d1f9a/tests/Unit/Core/Variables/StandardVariableProviderTest.php#L269

**Comment by lolli42** [comment]
Uh. Probably my bad, I made Daniel create this issue ;)

**Comment by ervaude** [comment]
Haha, glad this already works. All the better!
