### ISSUE TITLE
Allow invalid Fluid tags inside f:comment

### ISSUE THREAD

**Issue by georgringer** [TYPO3/Fluid#894]
this is a duplicate of https://forge.typo3.org/issues/97835 to have it in correct project

> Currently i update all <f:widget.paginate>
> if i wrap this widget with f:comment the f:widget.paginate still throws an error.
> I now i have to remove this widget, but for testing i want wrap this in a comment to write the new code.
> i think fluid should ignore code which is wrapped with comments

**Comment by georgringer** [comment]
wtf about the name

**Comment by mbrodala** [comment]
Yup. In any case this doesn't work:

```
<f:cache.disable><f:widget.paginate></f:widget.paginate></f:cache.disable>
```

This still throws the `The ViewHelper "<f:widget.paginate>" could not be resolved.` error.

**Comment by s2b** [comment]
Side note: These cache.* ViewHelpers are really confusing and will probably be deprecated in the future.

**Comment by mbrodala** [comment]
As a first step making `f:comment` like expected and described here would likely help. Evidently "disabling the compiler" also is not enough, since we'd actually need a "disable the parser" flag.

**Comment by lolli42** [comment]
Yes. We're deep in the parser here.

The current "solution" is documented in f:comment: "<f:comment><![CDATA[<f:some.invalid.syntax />]]></f:comment>".
Wrap the content in CDATA works. Reason: The NamespaceDetectionTemplateProcessor *removes* any CDATA wrapped content in an early step.

CDATA is of course ugly and it requires this manual interaction.

I think fluid has currently no solution to "stop" parsing sub elements.

And it gets worse: ext:styleguide has this usecase: It has a code viewhelper that should output html. If that code contains fluid VH's, those are interpreted - similar to the f:comment scenario. The CDATA "solution" does not work here, since the entire content vanishes ...

What we would need is a registry of VH's, to tell the parser if a VH is used in a template, the template parsing should stop. It looks as if this requires to make the regex $SPLIT_PATTERN_TEMPLATE_DYNAMICTAGS more dynamic, so fluid splits these parts differently on parser level. Such a change will require a bit of refactoring and a good solution for the registry.

**Comment by lolli42** [comment]
Related: #808, #474

**Comment by lolli42** [comment]
There is also `{parsing off}` to stop parsing an entire template, see #219

**Comment by s2b** [comment]
This will be possible with Fluid v4, the change has just been merged.

**Comment by rr-it** [comment]
This should work to use anything (invalid) inside a comment:

```
<f:comment><!-- <f:some.invalid.syntax /> --></f:comment>
```

**Comment by mbrodala** [comment]
No need for the additional HTML/XML comment:

```xml
<f:comment><f:some.invalid.syntax /></f:comment>
```
