### ISSUE TITLE
RenderingContext does not use view

### ISSUE THREAD

**Issue by kitsunet** [TYPO3/Fluid#96]
Hi,

slowly starting to get into the code and I wonder why this is done (why is $view a dependency of the RenderingContext):
https://github.com/TYPO3Fluid/Fluid/blob/master/src/Core/Rendering/RenderingContext.php#L121

I don't see a getter nor any usage of $this->view in there. So IMHO it just complicates the creation process as the View depends on the Context and this cross dependency is not really nice.

**Comment by NamelessCoder** [comment]
Hi Christian,

Thanks for looking into the code.

I agree that it's less than ideal that we have View on the RenderingContext. There is a reason though - as always - but an alternative solution was never created/discussed and could potentially require a breaking change.

The reason for having View on RenderingContext right now is that we need access to the View instance from `f:render` in order to call public methods to render partials and/or sections. No other class is currently aware of the View which is why RenderingContext has the instance. One of the reasons for making the constructor require the View but create it if not provided, is that we encourage custom RenderingContext classes which may be (if programmer decides) coupled to a specific View class.

On a side note, this was also the case in Flow's Fluid as well as CMS Fluid - although on those, the constructor would not create the instance (instead, template rendering would break if `f:render` was used and `setView()` had not been called on RenderingContext).

It might be possible to avoid the constructor creation but that would put this instance preparation requirement on another place and make the RenderingContext harder to create (like it was before, but now the RenderingContext has a much more prominent role).

The alternative might be to move it to ParsedTemplate/ParsingState, but I'm not sure without checking, whether or not that instance is consistently available to `f:render` in compiled and uncompiled modes alike.

Suggestions are welcome! If any part of the reasoning above needs further explaining please fire away ;)

**Comment by kitsunet** [comment]
Hey, wanted to come back to this. The current codebase uses `$this->viewHelperVariableContainer->getView()` inside the `RenderViewHelper` and this view again is set `\TYPO3Fluid\Fluid\View\AbstractTemplateView::initializeRenderingContext`, via `$this->baseRenderingContext->getViewHelperVariableContainer()->setView($this);` so I think the view property inside the `RenderingContext` itself is definitely unused and could be removed making this contruct much nicer to handle IMHO.

**Comment by NamelessCoder** [comment]
It does all (currently, judging from official implementations) look like only ViewHelperVariableContainer needs to know about the View. And since https://github.com/TYPO3Fluid/Fluid/commit/a7b9c7260201689d06734d294eb8e43891eb9224 that View would be assigned if you 1) do setRenderingContext or 2) do initializeRenderingContext which is also public API but happens when you do setRenderingContext (it is there so custom View classes will initialize also if not using setRenderingContext; Extbase could at some point in the future take advantage of this to avoid setRenderingContext).

So yes, it would appear this property and constructor argument can be removed, because we can now depend on AbstractTemplateView::initializeRenderingContext being called - which will always set the View into ViewHelperVariableController which is where it is needed.

I can't say for sure but I think the intention originally was to prepare ViewHelperVariableContainer as soon as RenderingContext was constructed, and this required the View as constructor parameter. This is, however, from a time well before the commit above - so it seems that now, *we can freely choose which one of these strategies we like better: the constructor argument or relying on initializeRenderingContext being called from the View to set the reference in ViewHelperVariableContainer*. Neither is documented as public API - once we decide, we should do that for the one that remains.

If we need a vote then I'm personally okay with removing this argument and property, and demanding initializeRenderingContext *must* be called at some point from custom View classes. And as far as I can tell with just CMS as framework reference, it wouldn't break anything to do so.

**Comment by kitsunet** [comment]
Same here, would also argue for initialize, alone because it seems bad to have two classes interdepend on each other in the constructor.
Thanks for following up!

**Comment by NamelessCoder** [comment]
We will have a great opportunity to solve this for 3.0 which will allow that breaking change.
